### ISSUE TITLE
[NOT PR] Twitter Login

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/mastodon#1]
This is trial version at https://mastwi.herokuapp.com/

* * * *
- [x] add omniauth-twitter
- [x] Twitter sign up
- [x] Twitter login
- [x] Sync profile image
- [ ] Suggest other accounts who they follow in Twitter
- [ ] Auto follow the same account in several servers：https://twitter.com/pandeiro245/status/853110026998734848

**Comment by kobake** [comment]
Are you planning to create PR of TwitterAuth for original mastodon?

**Comment by pandeiro245** [comment]
@kobake no! (like this https://github.com/dwango/mastodon/pulls )

**Comment by kobake** [comment]
got it
