### ISSUE TITLE
Twitter連携アプリ設定について

### ISSUE THREAD

**Issue by kobake** [pandeiro245/mastodon#4]
もしかして：mindia.jp のアプリケーションIDを使ってしまっている？（意図的？）

**Comment by pandeiro245** [comment]
@kobake 変更しました！（ついでにRead Onlyにしました）
https://mastwi.herokuapp.com/

![image](https://cloud.githubusercontent.com/assets/125965/25232515/98d83a2a-2616-11e7-90e0-28fa4958c873.png)

**Comment by kobake** [comment]
:+1:
